spring.application.name=hotelmanagmentsystem
spring.datasource.url =jdbc:mysql://localhost:3306/booking_system_db
spring.datasource.username = spring
spring.datasource.password = springstudent
spring.main.banner-mode=off
Jwt.secret = k3Jf8sK9lP2xZ7QvW1nT6bA0cXy9LmNoPqRsTuVwXy
# Show generated SQL queries
spring.jpa.show-sql=true

## Format the SQL (easier to read)
#spring.jpa.properties.hibernate.format_sql=true
#
## Show parameters (values bound to ?)
#logging.level.org.hibernate.type.descriptor.sql=TRACE
#
## Show the SQL query execution
#logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=TRACE