spring.application.name=hotelmanagmentsystem
spring.datasource.url = ${DB_URL}
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}
Jwt.secret=${JWT_SECRET}

spring.main.banner-mode=off

# Show generated SQL queries
spring.jpa.show-sql=true

## Format the SQL (easier to read)
#spring.jpa.properties.hibernate.format_sql=true
#
## Show parameters (values bound to ?)
#logging.level.org.hibernate.type.descriptor.sql=TRACE
#
## Show the SQL query execution
#logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=TRACE

# Change Swagger UI URL
springdoc.swagger-ui.path=/docs
Jwt.refresh-token.expiration = 60480000
